databases:
  - name: moeda-academica-db
    databaseName: moeda_academica
    user: moeda_academica_user
    plan: free
    region: oregon

services:
  - type: web
    name: moeda-academica
    runtime: python
    plan: free
    region: oregon
    branch: main

    # 👇 CAMINHO DO SEU PROJETO DENTRO DO REPO
    rootDir: "Projetos/Lab03 - Sistema de Moeda Estudantil"

    buildCommand: "./build.sh"
    startCommand: "gunicorn moeda_estudantil.wsgi:application"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moeda-academica-db
          property: connectionString

      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: PYTHON_VERSION
        value: "3.12.0"

      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,.onrender.com"

      - key: EMAIL_HOST_USER
        value: "moeda.academica@gmail.com"

      - key: EMAIL_HOST_PASSWORD
        sync: false
