# Generated by Django 5.2.6 on 2025-09-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vantagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='vantagens/'),
        ),
        migrations.AlterField(
            model_name='vantagem',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
