# Generated by Django 5.2.6 on 2025-10-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_vantagem_imagem_alter_vantagem_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vantagem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
