# Generated by Django 5.2.6 on 2025-09-27 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENVIO', 'Envio (débito do professor)'), ('RECEBIMENTO', 'Recebimento (crédito do aluno)'), ('RESGATE', 'Resgate de vantagem (débito do aluno)')], max_length=15)),
                ('valor', models.PositiveIntegerField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=64)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos_relacionados', to=settings.AUTH_USER_MODEL)),
                ('cupom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.cupom')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_realizados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
