# Generated by Django 5.2.6 on 2025-10-04 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_add_conta_column_if_missing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresaparceira',
            options={'ordering': ['nome'], 'verbose_name': 'Empresa Parceira', 'verbose_name_plural': 'Empresas Parceiras'},
        ),
        migrations.RemoveField(
            model_name='empresaparceira',
            name='email',
        ),
        migrations.AddField(
            model_name='empresaparceira',
            name='conta',
            field=models.OneToOneField(blank=True, help_text='Usuário com papel EMPRESA/PARCEIRO que acessa o dashboard desta empresa.', limit_choices_to=models.Q(('role__in', ['EMPRESA', 'PARCEIRO'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_parceira', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empresaparceira',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empresaparceira',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='empresaparceira',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empresaparceira',
            name='nome',
            field=models.CharField(max_length=120),
        ),
    ]
