# Generated by Django 5.2.6 on 2025-10-05 19:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='gerado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito (Recebido)'), ('RESGATE', 'Resgate (Débito)'), ('ENVIO', 'Envio (Débito)')], max_length=10)),
                ('valor', models.PositiveIntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
