# Generated by Django 5.2.6 on 2025-10-05 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_vantagem_id'),
        ('wallet', '0002_alter_carteira_id_alter_cupom_gerado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='vantagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.vantagem'),
        ),
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
